---
version: 2.1

executors:
  circleci-python-pkg-agent:
    description: |
      Alpine Linux-based circleci primary container, based on feedyard/circleci-remote-docker. includes common tools
      for building, testing, and publishgin python pip packages.
    docker:
      - image: quay.io/feedyard/circleci-python-pkg-agent

jobs:

  dev-test:
    description: lint, test, package, push to pip-test area
    executor: circleci-python-pkg-agent
    steps:
      - checkout
      - run:
          name: setup
          command: |
            pip install -r dev-requirements.txt
            pip install -e .
      - run:
          name: lint
          command: pylint secretctl/
      - run:
          name: test and coverage
          command: |
            cc-test-reporter before-build
            coverage run --source=secretctl/ setup.py test
            coverage xml
            coverage report
            cc-test-reporter after-build  --coverage-input-type coverage.py -d

  dev-build:
    description: lint, test, package, push to pip-test area
    executor: circleci-python-pkg-agent
    steps:
      - checkout
      - run:
          name: validate package build
          command: |
            python3 setup.py sdist bdist_wheel
            python3 -m twine upload \
                    -u $PYPI_USERNAME \
                    -p $PYPI_PASSWORD \
                    --repository-url https://test.pypi.org/legacy/ \
                    dist/*

  publish:
    description: publish new version pip package
    executor: circleci-python-pkg-agent
    steps:
      - checkout
      - run:
          name: publish package build
          command: |
            python3 setup.py sdist bdist_wheel
            python3 -m twine upload \
                    -u $PYPI_USERNAME \
                    -p $PYPI_PASSWORD \
                    dist/*


workflows:
  secretctl--pipeline:
    jobs:
      - dev-test:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
      - dev-build:
          filters:
            branches:
              only: /master/
            tags:
              ignore: /.*/
          requires:
            - dev-test
      - approve-publish-package:
          type: approval
          requires:
            - dev-build
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - approve-publish-package
